const assert=require('node:assert/strict'),{Node,document}=require('./dom-harness.cjs');require('../js/business.js');const B=CompanyBusiness;let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++;};
const app=new Node();app.className='altool-ui';document.append(app);
const input=new Node('input');input.value='2024-02-29';input.validity={valid:true};app.append(input);const picker=B.datePicker(input);picker.open();const calendar=app.querySelector('.ui-calendar');ok(calendar.querySelectorAll('[data-date]').length===29,'leap-year calendar');calendar.querySelector('[data-date="2024-02-20"]').click();ok(input.value==='2024-02-20','date choice updates source');ok(calendar.hidden,'date choice closes popup');input.value='2026-02-30';picker.validate();ok(!input.validity.valid,'manual invalid date rejected');picker.destroy();ok(input.parentElement===app,'date teardown restores source');
const select=new Node('select');select.multiple=true;select.setAttribute('aria-label','부서');for(const [value,label,disabled]of [['FIN','재무팀',false],['HR','인사팀',false],['OLD','이전 조직',true]]){const o=new Node('option');o.value=value;o.textContent=label;o.disabled=disabled;select.append(o);}app.append(select);const multi=B.multiselect(select);multi.value=['FIN'];ok(multi.value.join(',')==='FIN','multiselect source values');const wrapper=select.parentElement;wrapper.querySelector('button').click();const search=wrapper.querySelector('input');search.value='인사';search.dispatchEvent(new Event('input'));const choices=wrapper.querySelectorAll('.ui-multi-option');ok(choices.length===1,'multi search filters');const check=choices[0].querySelector('input');check.checked=true;check.dispatchEvent(new Event('change'));ok(multi.value.join(',')==='FIN,HR','search preserves other selected values');multi.destroy();ok(!select.hidden&&select.parentElement===app,'multi teardown restores source');
const form=new Node('form'),field=new Node('div'),required=new Node('input');field.className='ui-field';required.willValidate=true;required.name='제목';required.validity={valid:false,valueMissing:true};form.append(field);field.append(required);app.append(form);ok(!B.validateForm(form),'form invalid');ok(form.querySelector('.ui-error-summary').textContent.includes('필수'),'Korean summary');ok(field.querySelector('.ui-field-error'),'inline error');required.validity={valid:true};ok(B.validateForm(form),'corrected form valid');ok(!field.querySelector('.ui-field-error'),'old inline errors removed');
const chart=new Node();app.append(chart);B.barChart(chart,{title:'증감',items:[{label:'A',value:-100},{label:'B',value:100},{label:'C',value:0}]});const bars=chart.querySelectorAll('.ui-bar-fill');ok(bars[0].style.left==='0%'&&bars[0].style.width==='50%','negative chart scale');ok(bars[1].style.left==='50%'&&bars[1].style.width==='50%','positive chart scale');ok(bars[2].style.width==='0%','zero bar');ok(chart.querySelector('table').textContent.includes('-100'),'accessible chart data');
const tree=new Node();B.tree(tree,[{id:'HQ',label:'본사',children:[{id:'FIN',label:'재무팀'}]}],{onSelect(item){tree.chosen=item.id;}});tree.querySelectorAll('button')[1].click();ok(tree.chosen==='FIN','tree selection');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
 const lookup=new Node(),code=new Node('input'),trigger=new Node('button'),name=new Node('span');name.setAttribute('data-lookup-name','');lookup.append(code,trigger,name);app.append(lookup);const pending=[];const api=B.lookup(lookup,{search:()=>new Promise(resolve=>pending.push(resolve))});api.open();const modal=app.querySelector('dialog');modal.querySelector('form').dispatchEvent(new Event('submit',{cancelable:true}));pending[1]([{code:'NEW',name:'새 결과'}]);await tick();pending[0]([{code:'OLD',name:'이전 결과'}]);await tick();ok(modal.querySelector('.ui-lookup-results').textContent.includes('NEW'),'stale response ignored');modal.querySelector('.ui-lookup-item').click();ok(code.value==='NEW'&&name.textContent==='새 결과','lookup commits code and name');api.destroy();
 const presets=new Node();app.append(presets);let data=[],applied;const preset=B.presets(presets,{key:'test',store:{async get(){return data;},async set(k,v){data=v;}},capture:()=>({department:['FIN']}),apply:value=>{applied=value;}});await preset.ready;presets.querySelector('input').value='내 조건';presets.querySelectorAll('button')[0].click();await tick();ok(data.length===1&&data[0].name==='내 조건','preset saved');presets.querySelectorAll('button')[1].click();await tick();ok(applied.department[0]==='FIN','preset restored');presets.querySelectorAll('button')[2].click();await tick();ok(data.length===0,'preset deleted');
 console.log(`PASS ${checks} DOM-contract checks (no browser layout emulation)`);
})().catch(e=>{console.error(e);process.exitCode=1;});
