/* Demo data/adapters only. Production code belongs in the host app. */
const B=CompanyBusiness,app=document.querySelector('.altool-ui'),$=id=>document.getElementById(id);
const period=B.dateRange($('period'));B.datePicker($('accounting-month'),{month:true});
const localISO=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function setMonth(delta){const now=new Date();period.set(localISO(new Date(now.getFullYear(),now.getMonth()+delta,1)),localISO(new Date(now.getFullYear(),now.getMonth()+delta+1,0)));}
$('this-month').onclick=()=>setMonth(0);$('previous-month').onclick=()=>setMonth(-1);
const departments=[{code:'FIN',name:'재무팀'},{code:'SALES',name:'영업팀'},{code:'HR',name:'인사팀'},{code:'IT',name:'정보시스템팀'},{code:'PURCHASE',name:'구매팀'},{code:'LEGAL',name:'법무팀'}];
B.lookup($('department-lookup'),{title:'부서 검색',async search(query,{signal}){await new Promise(resolve=>setTimeout(resolve,250));if(signal.aborted)throw new DOMException('취소','AbortError');if($('lookup-fail').checked)throw new Error('Demo failure');return departments.filter(d=>(d.code+' '+d.name).toLowerCase().includes(query.toLowerCase()));},onSelect(row){$('lookup-selection').textContent=`선택: ${row.code} · ${row.name}`;}});
const multi=B.multiselect($('departments'));$('apply-multi').onclick=()=>{$('multi-result').textContent='현재 적용: '+(Array.from($('departments').selectedOptions).map(o=>o.label).join(', ')||'선택 없음');};
const drawer=B.dialog(app,'신청 상세',{drawer:true});drawer.actions.append(Object.assign(document.createElement('button'),{type:'button',textContent:'닫기',onclick:()=>drawer.close()}));
function detail(id){const row=Array.from(document.querySelectorAll('[data-row-select]')).find(n=>n.value===id).closest('tr');drawer.body.replaceChildren();const dl=document.createElement('dl');dl.className='ui-detail-grid';for(const [key,value]of [['신청 번호',id],['부서',row.cells[2].textContent],['신청 금액',row.cells[3].textContent+' 원'],['상태',row.cells[4].textContent]]){const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;div.append(dt,dd);dl.append(div);}drawer.body.append(dl);drawer.open();}
$('open-drawer').onclick=()=>detail('REQ-0091');document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));
const table=B.tableTools($('requests-table'),{async onAction(action,ids){const accepted=await B.confirm(app,{title:action==='approve'?'선택 승인':'선택 반려',message:`선택한 ${ids.length}건을 ${action==='approve'?'승인':'반려'}할까요?`,action:action==='approve'?'승인':'반려'});if(!accepted)return;for(const box of document.querySelectorAll('[data-row-select]')){if(!ids.includes(box.value))continue;const status=box.closest('tr').querySelector('.ui-status');status.textContent=action==='approve'?'완료':'반려';status.dataset.status=action==='approve'?'success':'error';box.checked=false;}table.refresh();$('batch-result').textContent=`${ids.length}건 ${action==='approve'?'승인':'반려'} 완료 (예시)`;B.toast(app,$('batch-result').textContent);}});
$('show-department').onchange=e=>table.setColumn(2,e.target.checked);
$('download-csv').onclick=()=>{const rows=[['신청 번호','부서','금액','상태'],...Array.from(document.querySelectorAll('#requests-table tbody tr')).map(tr=>[tr.cells[1].textContent,tr.cells[2].textContent,tr.cells[3].dataset.sortValue,tr.cells[4].textContent])];const quote=value=>'"'+String(value).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='requests-demo.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const form=$('request-form'),guard=B.dirtyGuard(form);form.onsubmit=e=>{e.preventDefault();$('save-error').hidden=true;if(!B.validateForm(form))return;const saved=guard.capture();B.busy($('save-request'),async()=>{await new Promise(resolve=>setTimeout(resolve,500));if($('save-fail').checked){$('save-error').textContent='저장하지 못했습니다. 입력 내용은 유지됩니다. 연결을 확인한 뒤 다시 저장하세요.';$('save-error').hidden=false;return;}guard.markClean(saved);B.toast(app,'저장되었습니다. (예시)');});};$('form-cancel').onclick=async()=>{if(await guard.mayLeave(app)){form.reset();guard.markClean();form.querySelector('.ui-error-summary').hidden=true;form.querySelectorAll('[aria-invalid]').forEach(n=>n.removeAttribute('aria-invalid'));$('save-error').hidden=true;}};
B.tree($('organization'),[{id:'HQ',label:'본사',expanded:true,children:[{id:'MGMT',label:'경영지원',expanded:true,children:[{id:'FIN',label:'재무팀'},{id:'HR',label:'인사팀'}]},{id:'SALES',label:'영업팀'},{id:'IT',label:'정보시스템팀'}]}],{onSelect(item){$('tree-result').textContent=`선택: ${item.label} (${item.id})`;}});
B.timeline($('approval-history'),[{status:'success',statusLabel:'완료',actor:'김민수 · 신청',time:'2026-09-10T09:10:00+09:00',timeLabel:'2026-09-10 09:10',comment:'예산 사용 신청을 등록했습니다.'},{status:'success',statusLabel:'완료',actor:'이서연 · 검토',time:'2026-09-10T10:05:00+09:00',timeLabel:'2026-09-10 10:05',comment:'증빙 자료를 확인했습니다.'},{status:'progress',statusLabel:'진행',actor:'박준호 · 승인',time:'2026-09-10T10:06:00+09:00',timeLabel:'2026-09-10 10:06',comment:'승인을 기다리고 있습니다.'}]);
const memory=new Map();B.presets($('filter-presets'),{key:'demo:user:budget:v1',store:{async get(key){return memory.get(key)||[];},async set(key,value){memory.set(key,structuredClone(value));}},capture(){return {from:$('date-from').value,to:$('date-to').value,departments:multi.value};},apply(value){period.set(value.from||'',value.to||'');multi.value=Array.isArray(value.departments)?value.departments:[];$('preset-result').textContent='저장한 조건을 불러왔습니다. 조회 또는 선택 적용 후 결과에 반영됩니다.';}});
const budget=[{label:'재무팀',value:1250},{label:'영업팀',value:3400},{label:'정보시스템팀',value:5200},{label:'인사팀',value:780}];const chart=(items,title)=>B.barChart($('department-chart'),{title,unit:'만원',items});chart(budget,'부서별 예산');$('chart-budget').onclick=()=>chart(budget,'부서별 예산');$('chart-difference').onclick=()=>chart([{label:'재무팀',value:150},{label:'영업팀',value:-240},{label:'정보시스템팀',value:380},{label:'인사팀',value:0}],'전월 대비 증감');
function state(type){const message={error:'서버에서 데이터를 가져오지 못했습니다.',forbidden:'해당 업무의 이용 권한을 담당자에게 요청하세요.',expired:'입력 중인 내용의 보존 여부를 확인한 뒤 다시 로그인하세요.',empty:'조회조건을 변경한 뒤 다시 조회하세요.',loading:'잠시 기다려 주세요.'}[type];B.systemState($('system-state'),{type,message,onAction:type==='loading'?undefined:()=>{$('state-result').textContent=type==='error'?'재시도 요청 예시입니다. 실제 앱에서는 조회 함수를 연결합니다.':type==='expired'?'실제 앱에서는 회사 로그인으로 연결합니다.':type==='forbidden'?'실제 앱에서는 권한 신청 또는 담당자 안내로 연결합니다.':'조회조건 영역으로 이동했습니다.';if(type==='empty')$('date-from').focus();}});}state('error');document.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>state(b.dataset.state));
